name: test
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ["nightly", "stable"]

    steps:
      - uses: actions/checkout@v7
      - name: Run tests
        uses: lumen-oss/nvim-busted-action@v1.2.0
        with:
          nvim_version: ${{ matrix.neovim-version }}
